use_frameworks!

platform :ios, '13.0'

target 'MVVMR_Example' do
  pod 'MVVMR', :path => '../'

  target 'MVVMR_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 2.2.0'
    pod 'Nimble', '~> 8.0.7'
  end
end
